### ISSUE TITLE
What does a unique_company_constraint mean when updating users?

### ISSUE THREAD

**Issue by timjnh** [intercom/intercom-node#197] opened 2018-04-27 14:02 UTC
## Version info
  - intercom-node version: 2.9.1
  - Node version: 6.x

No bug, just trying to gather information.  We've been getting unique_company_constraint responses from the API occasionally when updating users via intercomClient.users.update.  The users are something along the lines of

    {
        "user_id": "someUserId",
        "email": "abc123@somewhere.com",
        "name": "Joe Schmoe",
        "companies": [{"company_id": "someCompanyId"}]
    }

It's possible that multiple users are being uploaded at the same time with the same new, company id.  Are we just hitting random race conditions where both requests are triggering the creation of the company simultaneously?

**Comment by choran** [comment] 2018-04-27 14:49
hmmm .... yeah, that should only occur when the company already exists.
But if you are just updating users then it should either create the company if it doesnt exist or else just update the user if the company does exist.  The whole point of this is to eliminate the need for you to check it. Are you creating companies elsewhere that might create a race condition?

**Comment by timjnh** [comment] 2018-04-27 15:42
At the moment, no, we are only calling the users.update method.  We're doing it a lot in parallel though so I wouldn't be surprised if we issued two requests to create separate users that were both on the same company at very nearly the same time.

**Comment by choran** [comment] 2018-10-09 09:58
HI @timjnh 
I have been unable to reproduce this issue. I looked through the errors and I do think it is a race condition if you are performing these operations in parallel. The update operations seems to occur correctly. So it must occur when two operations are executed almost simultaneously and one creates the company before the other one sees that it has been created.  
I will close this issue since I am not sure if there is much we can do here, i.e. it is not an SDK issue. Hopefully, you might be able to limit the potential for the parallel operations or, alternatively, retry this if you receive this error since it should be able to update the user subsequently.
thanks

**Closed by choran** 2018-10-09 09:58 UTC
Labels: node, question
