### ISSUE TITLE
Geting 404 for events api call

### ISSUE THREAD

**Issue by AlmogRnD** [intercom/intercom-node#145] opened 2017-03-17 05:15 UTC
I'm getting 404 when I try to send a custom event 
Here is my code 
``` 
doc.profileIds.forEach(function(profileIds) {
    console.log(profileIds);
      let profile = Profiles.findOne({_id:profileIds});
      console.log(profile.email);
    
      client.events.create({
      event_name: 'loop started',
      created_at: 1439826340,
        email: profile.email,
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
````

**Comment by semeano** [comment] 2017-04-26 18:50
Same here.

**Comment by Skaelv** [comment] 2017-06-06 13:15
I was unable to reproduce with an existing user: 

```javascript
client.events.create({
      event_name: 'loop started',
      created_at: 1439826740,
        email: 'test_dx_NaN@example.com',
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
```
returns `202`: 

![image](https://cloud.githubusercontent.com/assets/5072452/26830850/235a0e74-4ac2-11e7-8733-6a9986a5260c.png)

I'm only able to reproduce when trying to submit an event with an inexistent email: 
```javascript
client.events.create({
      event_name: 'loop started',
      created_at: 1439826740,
        email: 'test_dx_NaN@example.com',
        metadata: {status: true}
      }, function (d) {
      console.log(d.statusCode);
      });
  });
```
returns `404`.
Can you try again making sure the email you are using is associated to an existing user in intercom?

**Comment by choran** [comment] 2017-08-25 13:52
Hi @AlmogRnD 
I am not sure if you were able to resolve this? If you are still having issue then please let us know. I will close it for now since it looks like this was no longer an issue but feel free to reopen if you are still experiencing issues.
Thanks
Cathal

**Closed by choran** 2017-08-25 13:52 UTC
