### ISSUE TITLE
listBy throws "Multiple existing users match this email address"

### ISSUE THREAD

**Issue by rubenstolk** [intercom/intercom-node#155] opened 2017-06-27 09:54 UTC
## Version info
  - intercom-node version: 2.8.8
  - Node version: 7.x

## Expected behavior
While using the `listBy` call I would expect to get more than one user if multiple users exists with the same email address (searching in Intercom UI shows me two users) but still I get this error as if I was trying to do a `findOne`

## Actual behavior
Give me both the users that exist in Intercom (searching in Intercom UI shows me two users)

## Steps to reproduce
 1. Make sure two users exist with the same email address
 2. `intercom.listBy({ email: someEmailAddress })`

**Comment by choran** [comment] 2017-08-25 14:18
Hi @rubenstolk 
I just wanted to clarify whether you are referring to leads or users?
if it is users then listBy should only be used with tags or segments:
```
// List users by tag or segment
client.users.listBy({ tag_id: 'haven' }, callback);
```
But it should work with leads.
I tried it out and confirmed that it works with leads.
The issue with the users is not an SDK issue but a restriction on the API itself where it cannot return multiple values for users with the same identifiers. We are looking at this internally to see if we can allow it via the API. But at the moment that is an API issue rather than an SDK one.

Just wanted to clarify which case you were referring to
Thanks
Cathal

**Comment by choran** [comment] 2017-09-07 16:02
Hi @rubenstolk 
Just checking if you has any update here?
As noted, it looks like the this is due to API behaviour rather than as issue with the SDK.
So I will close this issue for now unless you have an update. In which case feel free to reopen
Thanks
Cathal

**Closed by choran** 2017-09-07 16:02 UTC
