### ISSUE TITLE
Type issue while using Intercom-Version headers

### ISSUE THREAD

**Issue by mhnpd** [intercom/intercom-node#363] opened 2023-06-01 10:08 UTC
## Version info

-   intercom-node version: 4.0.0
-   Node version: 16

## Expected behavior
HeadersDefaults should be extended to support the headers

## Actual behavior
<img width="902" alt="image" src="https://github.com/intercom/intercom-node/assets/33191954/57a5c557-d7f7-4986-9f4d-0692f656f15d">

## Steps to reproduce

1. Try to set a intercom version using library in typescript project

**Comment by colmdoyle** [comment] 2023-06-01 10:26
Looks like a dupe of https://github.com/intercom/intercom-node/issues/326, you can track there, or re-open if I'm missing something.

**Closed by colmdoyle** 2023-06-01 10:26 UTC
