### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by workdoer** [intercom/intercom-node#189] opened 2018-03-02 14:44 UTC
I see error here - https://github.com/intercom/intercom-node/blob/master/lib/client.js#L146

I've got:
TypeError: Cannot read property 'error' of undefined
    at callback (/var/www/html/node_modules/intercom-client/dist/client.js:221:29)
    at Request._callback (/var/www/html/node_modules/intercom-client/dist/client.js:137:13)
    at self.callback (/var/www/html/node_modules/intercom-client/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/var/www/html/node_modules/intercom-client/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1296:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

## Version info
  - intercom-node version: 2.9.1
  - Node version: 9.4.0

Sorry, I can't reproduce it, I just see this errors in logs.

Seems like you need to make check if "data" variable exists, before accessing error property.

**Comment by rhodgkins** [comment] 2018-03-02 21:27
#169

**Comment by choran** [comment] 2018-04-13 13:48
Since this is a duplicate of #169  I will close this our and track it in that issue
Thanks

**Closed by choran** 2018-04-13 13:48 UTC
