### ISSUE TITLE
Unable to accurately iterate through conversations

### ISSUE THREAD

**Issue by RyanThomasMusser** [intercom/intercom-node#211] opened 2018-08-08 19:09 UTC
In the paginated response to this call:

```
client.conversations.list(function(error, conversationList){
	if(error){
		return console.log("Error!");
	}else{
		return console.log(conversationList.body);
	}
});
```

I'm given this URL to call next: https://api.intercom.io/conversations?per_page=20&page=2

As conversations continue to bubble to the top, will this style of pagination continue to work? Given the aggressive rate limiting, I foresee continuously iterating over duplicate conversations and even worse, missing conversations as they bubble to the top of the queue. Is this true? Besides continuously checking if we've already indexed a conversation on our side, has anyone else dealt with this issue in a graceful and scalable manner?

**Comment by davidseek** [comment] 2018-09-07 19:47
+1

**Comment by choran** [comment] 2018-10-19 10:51
Hi @RyanThomasMusser 
I am not sure I fully understand the issue here. One way to clarify it might be to check if the issue is related to the way the API works or the SDK, i.e. is there something missing from the SDK that we provide in the API or is there something missing from the API itself.

For the [conversations API](https://developers.intercom.com/intercom-api-reference/reference#list-conversations) you can list it without any parameter (i.e. in node that would be an empty parameter {})and it will return all the conversation for your app. You can then sort it for admin or user. You can also sort it by parameters such as undated_at or created_at.

By sorting it or ordering it you should be able to address this issue by ensuring the newest/oldest are at the end or the start. 

I am not sure if you have used any of these parameters to see if the address you issue. I think they should prevent the duplication issue you noted. Either way, I think the node SDK allows you to order and sort the endpoint with all the options available in the SDK. So it there is an issue it would be an API issue.

For now I will close this but feel free to re-open if you think I have misunderstood your query or if you are encountering a problem when listing your conversations

**Closed by choran** 2018-10-19 10:51 UTC
Labels: node, question

**Comment by dobesv** [comment] 2021-05-25 19:55
I don't think the above comment addresses the original issue.  When you fetch conversations with no parameters, it only returns the first page of conversations.  If you request the second page, you might get some of the same ones again if new conversations have been opened between the requests.  However, this is a design problem with the intercom API itself so you would have to ask them to update their API to properly paginate even in the presence of changes.
