### ISSUE TITLE
non standard error handling in callbacks

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-node#139] opened 2017-01-25 09:12 UTC
According to the lib's docs [Callbacks section](https://github.com/intercom/intercom-node#callbacks):
> This client library supports two kinds of callbacks:

``` js
// Option #1
client.users.list(function (d) {
  // d is the response from the server
});

// Option #2
client.users.list(function (err, d) {
  // err is an error response object, or null
  // d is a successful response object, or null
});
```

How does Intercom know which style you want ? It checks the amount of arguments in your callback function and sends you each time a different one accordingly.

This is very confusing and non standard:
1. In Node world an error object should always return first and results second. 
2. Adds unnecessary "magic" to the callback function. The results you get are determined by the amount of arguments you passed. Not a good thing.
3. This approach favors response data over response error. In reality, you should check for response error 100% of the times. But checking response data is not always necessary (from my personal experience with Intercom's service, it's usually not necessary)

**Comment by stringbeans** [comment] 2017-02-08 20:24
this is actually very dangerous behaviour. consider the case where a team has linting setup and marks that one of the arguments in the callback is not being utilized (for whatever reason). this will cause very unexpected behaviour if that team member removes the unused arg

**Comment by stringbeans** [comment] 2017-02-12 21:51
as a side note, it would be GREAT if the data coming back (either from a promise or callback) could be JUST the response body and not the entire response object.

**Comment by choran** [comment] 2017-08-25 13:20
Hi @mderazon 
Just catching up with some older issues and wanted to follow up here.
Are you suggesting that it would be better to just have one version where accept two arguments and not allow the case for just the response?
I would be afraid now that people might be using this one argument method and would break if this was changed. 
But I do see what you are saying. I am just not sure at present if it is something we would change. One option might be to remove one of the examples from the docs and leave the one with both arguments. 
Will try and do some more digging here but let me know if you have any other thoughts in the mantime
Thanks
Cathal

**Comment by rhodgkins** [comment] 2018-04-04 17:03
@choran I really think the error handling should be fixed and released as a new major (breaking) version. 

The current way the callback handler is called (counting the parameters provided to the callback) makes for easy errors to occur...
If you just want to send a request are not interested in the response body you'd have code such as this (pretty standard node code):

```js
const event = {
   event_name: 'some_event',
   created_at: Math.round(Date.now() / 1000),
   user_id: 'some user ID'
}

client.events.create(event, err => {
   if (err) {
      // Do something to handle the error
   } else {
      // Success - event created
   }
})
```

Now with the current error handling this doesn't work:

* If the request errors the code actually crashes (I've created PR #191 to fix this).
* If the request succeeds the whole [`response data`](https://github.com/intercom/intercom-node/blob/8918db291ac15144c4d18148356ef5ec93088df8/lib/client.js#L153) is returned to the callback which, with nodes error first callback style means the `// Do something to handle the error` will be run - which is not what the consumer of your SDK wanted at all!
* If the request fails (due to `error.list` in response) it works fine.

**Comment by webmobiles** [comment] 2020-01-29 04:37
there is not standard error management ?
```

try {
  await client....
} cath (err) {
}
```

**Comment by hypeofpipe** [comment] 2022-01-21 19:15
This issue is addressed in the beta version. Now, the SDK supports only a promise based approach. https://github.com/intercom/intercom-node/wiki/Migration-guide#no-more-callbacks

**Closed by hypeofpipe** 2022-01-21 19:15 UTC
Labels: question, node
