### ISSUE TITLE
Node intercom client does not seem to work with api V2

### ISSUE THREAD

**Issue by SvemirskiHod** [intercom/intercom-node#265] opened 2020-03-23 18:17 UTC
## Version info
  - intercom-node version: ^2.11.0
  - Node version: 8.5.0

## Expected behavior
Updating/Creating/Listing intercom user behaves as expected when using methods such as
- `client.users.create()`
- `client.users.update()`
- `client.users.list()`

## Actual behavior
Callling any of these methods with app on version 2 causes an error. Specifically, the error comes back like this: `The requested resource does not exist; check your path and try again`.
 NOTE: Setting the API back to version 1 works as expected, without errors.

## Steps to reproduce
 1. Create an app as version 2
 2. Create/update/list users. Experience error.
 3. Set app as version 1 and try again. Things should work

**Comment by normdoow** [comment] 2020-03-27 23:01
So I guess I shouldn't use this library then....☹️

**Comment by SvemirskiHod** [comment] 2020-03-27 23:10
> So I guess I shouldn't use this library then....☹️

@normdoow You can still use it, but you will have to make sure your intercom app using version 1, not 2. You can configure this on your app settings.

**Comment by normdoow** [comment] 2020-03-27 23:16
@SvemirskiHod I think I want to be able to start out using the new stuff though.

**Comment by alete89** [comment] 2020-05-26 19:25
This issue should have more attention.

**Comment by nrkrishna** [comment] 2020-06-03 14:40
Ran into the same issue myself and thought I was doing something wrong. I was banging my head against a wall until I found this thread. Please get this fixed!

**Comment by wyattbenno777** [comment] 2020-06-03 23:51
Anyone working on this?

**Comment by normdoow** [comment] 2020-06-03 23:57
> Anyone working on this?

Doesn't appear to be.

**Comment by bneigher** [comment] 2020-06-20 00:15
wait what? why is the sdk dead? I can't paginate contacts doesn't look like the pages object is supported as is anymore

**Comment by AleksandrIvanenko** [comment] 2020-06-25 11:17
At least write about it in readme, I've spent about a day to figure it out...

**Comment by bradennapier** [comment] 2020-06-26 19:54
official intercom sdk for node doesnt support their latest api version for months :-P hah.  how embarassing

**Comment by bradennapier** [comment] 2020-06-27 10:29
I started on a replacement of this library implementing typescript nicely and adding the functionality i've been missing.  It isn't finished or ready to consume yet but it may be helpful to some of you.  The functions that are there do work 

https://github.com/bradennapier/intercomly

**Comment by ethanwillis** [comment] 2020-06-29 11:27
@bradennapier You're appreciated. It's a shame that this big company can't even throw a star your way. 

It's weird. They are working on bindings for a lot of other languages. But not Node. I think maybe there were issues internally? Because on their OFFICIAL docs they have broken links to their blog and twitter account right at the top of the page...... https://developers.intercom.com/intercom-api-reference/reference

**Comment by wyattbenno777** [comment] 2020-06-29 16:25
One could Intercom them for support. Probably a Ruby house.

**Comment by renatoargh** [comment] 2020-08-03 16:45
This is also broken for me. A time waster so far.

**Comment by marcelo-lopes** [comment] 2020-08-10 16:03
Facing the same issue here.
@choran or someone from Intercom, would you have any ETA for this to be fixed?
Thanks.

**Comment by JakeMaldonado** [comment] 2020-08-13 14:13
I contacted support and asked them to at least update the readme, that was about a month ago. It takes one second and It would save a lot of developers time before they find this thread. 🤦‍♂️

**Comment by AdamBCo** [comment] 2020-10-03 14:37
Any update on this?

**Comment by sebitoelcheater** [comment] 2020-10-28 13:43
😴

**Comment by DominikVavra** [comment] 2020-11-12 10:19
In **README** they are mentioning that you **CAN** add the intercom API version in the request headers. They somehow forgot to mention that **version 1.2 is the last working version** with this package :) So if you add this to your request:
```
const client = new Intercom.Client({ token: 'my_token' });
client.useRequestOpts({
  headers: {
    'Intercom-Version': 1.2
  }
});
```

It should work until you are able to work with 1.2 :)

**Comment by cuonghuynh** [comment] 2020-11-15 22:15
Thanks, @DominikVavra for the hint, 1.4 still working for users API :) Confirmed.

**Comment by seawatts** [comment] 2021-01-20 17:34
Any progress on here?

**Comment by Aarbel** [comment] 2021-01-25 17:03
same error, any progress then ?

**Comment by SvemirskiHod** [comment] 2021-01-26 17:34
I don't think anyone from intercom is even watching this

**Comment by victoryakaniru** [comment] 2021-04-07 14:27
Still no progress on this. It's 2021!

**Comment by Aarbel** [comment] 2021-04-07 14:29
Waiting for the update too

**Comment by Aarbel** [comment] 2021-04-07 14:29
Don't hesitate to notify intercom teams on their internal CSM Chat

**Comment by DomVinyard** [comment] 2021-11-14 15:07
any updates?

**Comment by hypeofpipe** [comment] 2022-01-21 19:20
This issue is addressed in the beta version. Now it supports the latest API - v2.X. https://github.com/intercom/intercom-node/wiki/Migration-guide#main-changes

**Closed by hypeofpipe** 2022-01-21 19:20 UTC
