### ISSUE TITLE
Add button to HTML email

### ISSUE THREAD

**Issue by dominhtri1995** [intercom/intercom-node#255] opened 2019-08-08 18:18 UTC
Hi,

Just wondering why I can't add a simple action button to HTML email using this endpoint: https://developers.intercom.com/intercom-api-reference/reference#admin-initiated-conversation

Is this a way to lure us to buy the Outbound Messages plan as well ? Even so, there are just so many use cases where we need to fully customize our emails using the API. 

Plz consider supporting this feature or at least let us add a standard action button at the end of an email.

**Comment by lloydliyu** [comment] 2020-07-21 12:00
Hey @dominhtri1995 :wave:

You should be able to add the button with the following in the body using the `personal` template.

```
<table class='intercom-container intercom-align-left'>
   <tbody>
      <tr>
         <td>
            <a class='intercom-h2b-button'>test</a>
         </td>
      </tr>
   </tbody>
</table>
```

We don't guarantee it, but it should work. This is more to do with the limitation of HTML with the API itself, rather than the SDK. I'd recommend reaching out tot he support team using the Messenger on https://intercom.com if you have any further questions on this, or want to log further HTML support as a feature request.

Closing this out as the issue is related the API rather than the SDK.

**Closed by lloydliyu** 2020-07-21 12:00 UTC
